snerd/amiibo/urls.py
from django.conf.urls import url

from . import views

#you have to add the views created bellow
urlpatterns = [
    # /amiibo/
    url(r'^$', views.IndexView.as_view(), name='index'),    #views.IndexView is the "class-based view" from the views.py file of this app "amiibo"
    # /amiibo/10/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),#or pk instead of amiibo_id??
    #  url(r'^series/(?P<pk>[0-9]+)/$', views.SeriesDetailView.as_view(), name='series_detail'),
    #  url(r'^universe/(?P<pk>[0-9]+)/$', views.UniverseDetailView.as_view(), name='universe_detail'),
]

snerd/games/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

snerd/snerd/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#for development static files
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'snerd.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

#    url(r'^$', include('amiibo.urls', namespace="amiibo")),                                 #use r'^$' for the domain home
    url(r'^games/',include('games.urls', namespace="games")),                       #games.urls is the urls.py file INSIDE the games APP
    url(r'^ice_cream/', include('ice_cream.urls', namespace="ice_cream")),     #ice_cream.urls is the urls.py file INSIDE the ice_cream APP       
    url(r'^amiibo/', include('amiibo.urls', namespace="amiibo")),                        #amiibo.urls is the urls.py file INSIDE the amiibo APP
    url(r'^admin/', include(admin.site.urls)),              
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#BELOW IS DEVELOPMENT CODE FOR SERVING STATIC FILES; DONT USE IN PRODUCTION!
if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]     

snerd/amiibo/models.py
from django.db import models

# Create your models here.


class AmiiboSeries(models.Model):
    amiibo_series_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200) # amiibo series/line name
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        db_table = 'amiibo_series'   # custom table name; I like this better
        verbose_name_plural = "amiibo series"
        
class AmiiboUniverse(models.Model):
    amiibo_universe_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200) # universe name
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        db_table = 'amiibo_universe'   #custom table name; I like this better
        
class Amiibo(models.Model): # MANY "amiibo characters" to ONE "universe" & MANY "amiibo characters" to ONE "series"
    amiibo_id = models.AutoField(primary_key=True)
    image = models.ImageField(upload_to='amiibo/', null=True, blank=True)   #creates folder called amiibo under the main media folder and uploads there
    name = models.CharField(max_length=200, verbose_name='character') # character name
    rating = models.DecimalField(max_digits=3, decimal_places=1, null=True, blank=True)
    universe = models.ForeignKey(AmiiboUniverse)    
    series = models.ForeignKey(AmiiboSeries)
    #release_date (hard to pin down exact dates for some..)
    #exclusive
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        db_table = 'amiibo'   # custom table name; I like this better
        verbose_name_plural = "amiibo"

snerd/amiibo/views.py
from django.shortcuts import get_object_or_404, render
# from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse
from django.views import generic
# from django.views.generic import DetailView
from .models import Amiibo
# from .models import Amiibo, AmiiboSeries, AmiiboUniverse


# Create your views here.


class IndexView(generic.ListView):
    template_name = 'amiibo/index.html'
    context_object_name = 'amiibo_list'

    def get_queryset(self):
        return Amiibo.objects.order_by('name')
           
# class IndexView(generic.ListView):
    # template_name = 'amiibo/index.html'
    # context_object_name = 'amiibo_series_list'

    # def get_queryset(self):
        # return AmiiboSeries.objects.order_by('name')
    
    # def get_context_data(self, **kwargs):
        # context = super(IndexView, self).get_context_data(**kwargs)
        # context['amiibo_universe_list'] = AmiiboUniverse.objects.order_by('name')
        # return context
        
# class SeriesDetailView(generic.DetailView):
    # model = AmiiboSeries
    # template_name = 'amiibo/series_detail.html'
   
# class UniverseDetailView(generic.DetailView):
    # model = AmiiboUniverse
    # template_name = 'amiibo/universe_detail.html'
    
class DetailView(generic.DetailView):
    template_name = 'amiibo/detail.html'
    model = Amiibo

snerd/games/views.py
from django.shortcuts import get_object_or_404, render
# from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse
from django.views import generic

from .models import Game

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'games/index.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        return Game.objects.order_by('title')
     
class DetailView(generic.DetailView):
    model = Game
    template_name = 'games/detail.html'

snerd/amiibo/templates/amiibo/detail.html
<h1>{{ amiibo.name }}</h1> {# or just {{ name }} #}

<h2>Series</h2>
<p>{{ amiibo.series }}</p>

<h2>Universe</h2>
<p>{{ amiibo.universe }}</p>

<h2>Rating</h2>
<p>{{ amiibo.rating }}</p>

 <img src="{{ amiibo.image.url }}">

snerd/amiibo/templates/amiibo/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Amiibo</title>
	<link rel ="stylesheet" type="text/css" href="{% static 'amiibo/style.css' %}">
	<script src="{% static 'amiibo/js/jquery-2.1.4.min.js' %}"></script>
	<script src="{% static 'amiibo/js/js_fade.js' %}"></script>
</head>

<body>
	
	<div>
		<h1>Amiibo</h1>
	</div>
	
	<ul>
	{% for amiibo in amiibo_list %}	{# for MODEL in .. #}
		<li>
			<a href="{% url 'amiibo:detail' amiibo.pk %}">
				<img src="{{ amiibo.image.url }}"> 
				<p>{{ amiibo.name }}</p>
			</a>
		</li>
	{% endfor %}
	</ul>
	
</body>
	
</html>

snerd/amiibo/templates/amiibo/series_detail.html
<!-- <h1>{{ amiiboseries.name }} Series</h1> {# or just {{ amiiboseries }} #} -->

<ul>
{% for series in amiiboseries.amiibo_set.all %}
    <li>{{ series.name }}</li> {# or {{ series }} #}
{% endfor %}
</ul>

snerd/amiibo/templates/amiibo/universe_detail.html
<!-- <h1>{{ amiiboseries.name }} Series</h1> {# or just {{ amiiboseries }} #} -->

<ul>
{% for universe in amiibouniverse.amiibo_set.all %}
    <li>{{ universe.name }}</li>
{% endfor %}
</ul>